events {
    worker_connections 1024;
}

http {
    # Definition der Backend-Server (unsere Apache Container)
    upstream edugame_backend {
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;

        location / {
            # Leitet die Anfragen an die definierte Upstream-Gruppe weiter
            proxy_pass http://edugame_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}